version: "3.9"
networks: 
  deploy-vnapi-network:
    driver: bridge
services:
  app:
    container_name: vn-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-vnapi-network
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moloko990
      POSTGRES_DB: vndb
    ports:
      - "5432:5432"
    networks:
      - deploy-vnapi-network
    volumes: 
      - ./vndb.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postresql/data
volumes:
  postgres-data:
