version: "3.9"
networks: 
  deploy-vnapi-network:
    driver: bridge
services:
  vn-api:
    container_name: vn-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443" # HTTPS порт
    networks:
      - deploy-vnapi-network
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moloko990
      POSTGRES_DB: vndb
    ports:
      - "5432:5432"
    networks:
      - deploy-vnapi-network
    volumes: 
      - ./vndb.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postresql/data
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - vn-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - deploy-vnapi-network

volumes:
  postgres-data:
